name: RRPGQuesting
version: 0.0.1
authors: [ShawnClake, QuinnBast]
main: com.openrubicon.questing.RRPGQuesting
depend: [RRPGCore]
database: true
website: https://github.com/OpenRubiconProject
commands:
      rrpg-questing:
               description: Spits out the current status of Rubicon Questing and its versions
               usage: /rrpg-questing